print("hello guilherme1")
print("hello guilherme2")
print("hello guilherme3")
print("hello guilherme4")
print("hello guilherme5")
print("hello Fenrir 1")
print("hello Fenrir 3")
print("hello Fenrir 2")
print("hello Fenrir 4")
print("hello guilherme6")
print("hello guilherme7")
print("hello guilherme8")
print("hello guilherme9")
