print("hello guilherme1")
print("hello guilherme2")
print("hello guilherme3")
print("hello guilherme4")
print("hello guilherme5")
print("hello Fenrir 1")
print("hello Fenrir 3")
print("hello Fenrir 2")
print("hello Fenrir 4")
print("hello guilherme6")
print("hello guilherme7")
print("hello guilherme8")
print("hello guilherme9")
print("hello Fenrir 5")
print("hello Fenrir 6")
print("hello Fenrir 7")
print("hello Fenrir 8")
print("hello Ian1")
print("hello Ian2")
print("hello Ian3")
print("hello Ian4")
print("hello Ian5")
print("hello Ian6")
print("hello aruak1")
print("hello aruak2")
print("hello aruak3")
print("hello aruak4")
print("hello aruak5")
